### ISSUE TITLE
[Bug] 高级统计报错：Error creating WebGL context.

### ISSUE THREAD

**Issue by clion007** [chaitin/SafeLine#1042]
### What happened?

最新版本6.6.1，进入高级统计界面，点3D出现错误页面：
Unexpected Application Error!
Error creating WebGL context.
Error: Error creating WebGL context.
    at new WebGLRenderer (https://genanbio.com:62580/assets/index-AOmEbMiA.js:4666:21895)
    at Function.$ (https://genanbio.com:62580/assets/index-AOmEbMiA.js:5179:7714)
    at u0 (https://genanbio.com:62580/assets/index-AOmEbMiA.js:4667:885)
    at Object.d0 [as renderObjs] (https://genanbio.com:62580/assets/index-AOmEbMiA.js:4667:841)
    at Function.$ (https://genanbio.com:62580/assets/index-AOmEbMiA.js:5182:10822)
    at u0 (https://genanbio.com:62580/assets/index-AOmEbMiA.js:4667:885)
    at d0 (https://genanbio.com:62580/assets/index-AOmEbMiA.js:4667:841)
    at https://genanbio.com:62580/assets/index-AOmEbMiA.js:5182:15593
    at Rj (https://genanbio.com:62580/assets/react-C_KpXKrM.js:32:24220)
    at Ik (https://genanbio.com:62580/assets/react-C_KpXKrM.js:32:42204)

### How we reproduce?

1. 登录最新版本雷池管理页面；
2. 在数据统计界面，进入高级统计；
3. 在下面的地图默认2D，点3D就报错，且不知道怎么切换回2D。

### Error log

2024/08/18 21:28:13 [ERROR] middleware gin@v1.9.1/context.go:174 check jwt failed: login expired
2024/08/18 21:28:13 [ERROR] middleware gin@v1.9.1/context.go:174 check jwt failed: login expired
2024/08/18 21:28:13 [ERROR] middleware gin@v1.9.1/context.go:174 check jwt failed: login expired
2024/08/18 21:28:13 [ERROR] middleware gin@v1.9.1/context.go:174 check jwt failed: login expired
2024/08/18 21:28:13 [ERROR] middleware gin@v1.9.1/context.go:174 check jwt failed: login expired
2024/08/18 21:28:13 [ERROR] middleware gin@v1.9.1/context.go:174 check jwt failed: login expired
2024/08/18 21:28:14 [ERROR] middleware gin@v1.9.1/context.go:174 check jwt failed: login expired
2024/08/18 21:28:14 [ERROR] middleware gin@v1.9.1/context.go:174 check jwt failed: login expired

**Comment by safe1ine** [comment]
fixed in 6.7.0
