### ISSUE TITLE
[Bug] 不知道是不是因为我机器内存太少的问题

### ISSUE THREAD

**Issue by bboysoulcn** [chaitin/SafeLine#242]
### 问题描述

oracle 免费 x86 云服务器升级报错

```bash
root@instance-20221011-0912:~# docker logs -f safeline-mario
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xb030c7]

goroutine 206 [running]:
gorm.io/gorm.(*DB).Transaction(0x0, 0xc001145d40, {0x0, 0x0, 0x0})
	/go/pkg/mod/gorm.io/gorm@v1.24.7-0.20230306060331-85eaf9eeda11/finisher_api.go:617 +0x67
git.in.chaitin.net/patronus/safeline-ce/mario/server/plumber/stat/summary.(*Service).systemStatistics(0x48?, {0x0, 0xc001151bc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...})
	/builds/patronus/safeline-ce/mario/server/plumber/stat/summary/service.go:148 +0x165
created by git.in.chaitin.net/patronus/safeline-ce/mario/server/plumber/stat/summary.newTotalAccessStatTask.func1
	/builds/patronus/safeline-ce/mario/server/plumber/stat/summary/tasks.go:149 +0xf6
```

重启容器就好了

**Comment by zclaiqcc** [comment]
如果是重启能恢复的话，目前怀疑可能是启动顺序问题，我们尝试复现一下，后面版本也考虑下如何优化。

**Comment by bboysoulcn** [comment]
3.1.0还是没有修复

**Comment by bboysoulcn** [comment]
这次更新貌似可以了

**Comment by bboysoulcn** [comment]
3.2.0

**Comment by zclaiqcc** [comment]
嗯师傅再观察一段时间吧，我们增加了容器启动顺序的控制。issue 先关闭了，又遇到的话师傅再 Reopen
