### ISSUE TITLE
[Bug] safeline-mario在内存不足300MB时会出现报错，导致崩溃

### ISSUE THREAD

**Issue by sunnywangzi** [chaitin/SafeLine#756]
### 问题描述

防火墙这个模块好像在内存不足300MB时会出现报错` panic: runtime error: invalid memory address or nil pointer dereference`，不管有没有使用swap
启动一段时间后就会出现，模块崩溃，反复被重启，然后就会导致机器高负载

```

root@wang:~# docker logs 93214b249925 -f
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x994327]

goroutine 250 [running]:
gorm.io/gorm.(*DB).Transaction(0x0, 0xc000d13d00, {0x0, 0x0, 0x0})
        /go/pkg/mod/gorm.io/gorm@v1.24.7-0.20230306060331-85eaf9eeda11/finisher_api.go:617 +0x67
git.in.chaitin.net/patronus/safeline-ce/mario/server/plumber/stat/summary.(*Service).systemStatistics(0xedd87493e?, {0x0, 0xc001308410, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...})
        /work/server/plumber/stat/summary/service.go:152 +0x165
created by git.in.chaitin.net/patronus/safeline-ce/mario/server/plumber/stat/summary.newTotalAccessStatTask.func1
        /work/server/plumber/stat/summary/tasks.go:180 +0xf6

```

### 版本号

5.0.0

### 复现方法

启动一段时间后就会出现，报错` panic: runtime error: invalid memory address or nil pointer dereference`导致模块崩溃，模块反复被重启

### 期望的结果

修复

**Comment by yrluke** [comment]
能不能再多提供一些log，另外，我猜这个原因不是因为内存导致的，我猜可能是因为pg已经挂掉了

**Comment by sunnywangzi** [comment]
我现在单独拿了一台服务器来做waf，原先的日志已经没有了
另外，我觉得应该还是mario的问题，因为在mario崩溃之后反复自动重启的时候 只需要docker手动重启mario容器就会恢复一段时间，然后同样的问题又会出现，所以我觉得应该跟pg没关系
