### ISSUE TITLE
网站访问异常

### ISSUE THREAD

**Issue by andyoulovexy** [chaitin/SafeLine#806]
### 问题描述

刚开始接入没什么问题，接入了半个月，组件很多报错，网站也是断断续续能访问

### 版本号

4.3.2

### 复现方法

2024/04/10 17:27:04 [ERROR] controller runtime/panic.go:914 reflect: reflect.Value.SetInt using unaddressable value
2024/04/10 17:27:06 [ERROR] controller runtime/asm_amd64.s:1650 task panic, auto restart resources
2024/04/11 00:01:18 [ERROR] controller runtime/panic.go:914 reflect: reflect.Value.SetInt using unaddressable value
2024/04/11 00:01:20 [ERROR] controller runtime/asm_amd64.s:1650 task panic, auto restart resources
2024/04/11 00:02:33 [ERROR] controller runtime/panic.go:914 reflect: reflect.Value.SetInt using unaddressable value
2024/04/11 00:02:35 [ERROR] controller runtime/asm_amd64.s:1650 task panic, auto restart resources
2024/04/11 00:03:48 [ERROR] controller runtime/panic.go:914 reflect: reflect.Value.SetInt using unaddressable value
2024/04/11 00:03:50 [ERROR] controller runtime/asm_amd64.s:1650 task panic, auto restart resources
2024/04/11 00:05:03 [ERROR] controller runtime/panic.go:914 reflect: reflect.Value.SetInt using unaddressable value
2024/04/11 00:05:05 [ERROR] controller runtime/asm_amd64.s:1650 task panic, auto restart resources
2024/04/11 00:06:18 [ERROR] controller runtime/panic.go:914 reflect: reflect.Value.SetInt using unaddressable value
2024/04/11 00:06:20 [ERROR] controller runtime/asm_amd64.s:1650 task panic, auto restart resources
2024/04/11 00:07:33 [ERROR] controller runtime/panic.go:914 reflect: reflect.Value.SetInt using unaddressable value
2024/04/11 00:07:35 [ERROR] controller runtime/asm_amd64.s:1650 task panic, auto restart resources
2024/04/11 00:08:48 [ERROR] controller runtime/panic.go:914 reflect: reflect.Value.SetInt using unaddressable value
2024/04/11 00:08:50 [ERROR] controller runtime/asm_amd64.s:1650 task panic, auto restart resources
2024/04/11 00:10:03 [ERROR] controller runtime/panic.go:914 reflect: reflect.Value.SetInt using unaddressable value
2024/04/11 00:10:05 [ERROR] controller runtime/asm_amd64.s:1650 task panic, auto restart resources
2024/04/11 00:11:18 [ERROR] controller runtime/panic.go:914 reflect: reflect.Value.SetInt using unaddressable value
2024/04/11 00:11:20 [ERROR] controller runtime/asm_amd64.s:1650 task panic, auto restart resources
2024/04/11 00:12:33 [ERROR] controller runtime/panic.go:914 reflect: reflect.Value.SetInt using unaddressable value
2024/04/11 00:12:35 [ERROR] controller runtime/asm_amd64.s:1650 task panic, auto restart resources
2024/04/11 00:50:18 [ERROR] controller runtime/panic.go:914 reflect: reflect.Value.SetInt using unaddressable value
2024/04/11 00:50:20 [ERROR] controller runtime/asm_amd64.s:1650 task panic, auto restart resources
2024/04/11 00:51:33 [ERROR] controller runtime/panic.go:914 reflect: reflect.Value.SetInt using unaddressable value
2024/04/11 00:51:35 [ERROR] controller runtime/asm_amd64.s:1650 task panic, auto restart resources

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x994327]

goroutine 297 [running]:
gorm.io/gorm.(*DB).Transaction(0x0, 0xc001858d40, {0x0, 0x0, 0x0})
        /go/pkg/mod/gorm.io/gorm@v1.24.7-0.20230306060331-85eaf9eeda11/finisher_api.go:617 +0x67
git.in.chaitin.net/patronus/safeline-ce/mario/server/plumber/stat/summary.(*Service).systemStatistics(0x0?, {0x0, 0xc0017eec30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...})
        /work/server/plumber/stat/summary/service.go:152 +0x165
created by git.in.chaitin.net/patronus/safeline-ce/mario/server/plumber/stat/summary.newTotalAccessStatTask.func1
        /work/server/plumber/stat/summary/tasks.go:180 +0xf6

[2024-04-11 06:56:57.682] [1] [ERROR] failed to send detect response, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
[2024-04-11 07:05:52.719] [1] [ERROR] failed to send detect response, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
[2024-04-11 07:05:55.986] [1] [ERROR] failed to send detect response, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
[2024-04-11 07:11:12.186] [1] [ERROR] failed to send detect response, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
[2024-04-11 07:11:16.234] [1] [ERROR] failed to send detect response, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
[2024-04-11 07:11:16.236] [1] [ERROR] failed to send detect response, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
[2024-04-11 07:21:59.033] [1] [ERROR] failed to send detect response, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
[2024-04-11 07:22:56.651] [1] [ERROR] failed to send detect response, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
[2024-04-11 07:28:50.987] [1] [ERROR] failed to send detect response, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
[2024-04-11 07:28:52.707] [1] [ERROR] failed to send detect response, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
[2024-04-11 07:28:53.581] [1] [ERROR] failed to send detect response, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
[2024-04-11 07:28:53.583] [1] [ERROR] failed to send detect response, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
[2024-04-11 07:32:00.984] [1] [ERROR] failed to send detect response, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
[2024-04-11 07:32:01.074] [1] [ERROR] failed to send detect response, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
[2024-04-11 07:32:01.078] [1] [ERROR] failed to send detect response, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
[2024-04-11 07:32:01.078] [1] [ERROR] failed to send detect response, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
[2024-04-11 07:32:03.082] [1] [ERROR] failed to send detect response, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
[2024-04-11 07:32:05.516] [1] [ERROR] failed to send detect response, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
[2024-04-11 07:32:05.516] [1] [ERROR] failed to send detect response, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
[2024-04-11 07:50:56.525] [1] [ERROR] failed to send detect response, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
[2024-04-11 07:50:56.525] [1] [ERROR] failed to send detect response, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
[2024-04-11 08:18:56.946] [1] [ERROR] failed to send detect response, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
[2024-04-11 08:18:56.948] [1] [ERROR] failed to send detect response, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
[2024-04-11 08:50:40.190] [1] [ERROR] failed to send detect response, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
[2024-04-11 08:50:40.276] [1] [ERROR] failed to send detect response, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
[2024-04-11 08:50:42.212] [1] [ERROR] failed to send detect response, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
[2024-04-11 08:51:53.710] [1] [ERROR] failed to send detect response, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
[2024-04-11 08:52:20.204] [1] [ERROR] failed to send detect response, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
[2024-04-11 08:55:12.132] [1] [ERROR] failed to send detect response, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
[2024-04-11 09:51:30.979] [1] [ERROR] failed to send detect response, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }

### 期望的结果

期望正常

**Comment by yrluke** [comment]
建议检查一下负载

**Comment by xbingW** [comment]
问题反馈请移步 https://rivers.chaitin.cn/discussion
